<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUcaYTO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUcaYTO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJUcaYTO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJUcaYTO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJUcaYTO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JUcaYTO',
    'container.build_id' => '2da5017e',
    'container.build_time' => 1576529859,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUcaYTO');
