<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7mWrrbM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7mWrrbM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7mWrrbM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7mWrrbM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7mWrrbM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7mWrrbM',
    'container.build_id' => '1059e15e',
    'container.build_time' => 1573991346,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7mWrrbM');
