<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGEDTQo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGEDTQo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGEDTQo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGEDTQo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPGEDTQo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PGEDTQo',
    'container.build_id' => '8ae17d59',
    'container.build_time' => 1573596405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGEDTQo');
